### ISSUE TITLE
feat: パンくずリストの作成（UI）

### ISSUE THREAD

**Issue by ogakuzuko** [do-it-if-i-can/client#39]
画像参考

![CleanShot 2022-02-28 at 03 01 04@2x](https://user-images.githubusercontent.com/70119474/155894072-adc653f9-84fd-4155-8a88-05fdcdbb2f70.png)

**Comment by miyasan31** [comment]
これ仕様変更で無くなってるみたいですね👀

**Comment by ogakuzuko** [comment]
@miyasan31 
お、そうだったのね！
あざます！Closeします🚫

**Comment by ogakuzuko** [comment]
@miyasan31 
お、そうだったのね！あざます！
Closeします🚫
