### ISSUE TITLE
chore:全てのアイコンをHeroIconにしたい

### ISSUE THREAD

**Issue by miyasan31** [do-it-if-i-can/client#59]
画面内のアイコン見る限り全てHeroIcon使ってるので（多分恐らく）アイコン類はheroIconベースのものに変えたいなと思いました🤔

色系をfillとかで管理しなくて良くなるので実装が楽になると思われます！
そのままclassNameにTailwindCSS当てる感じでw-4, h-4, text-red-400とか当てれるかと！
> 今あるアイコンはFigmaからとってきたやつなのかな？tailwindのtext-red-300とかが効いてくれない

↓↓↓このリンクたち全然仕事してない

削除→https://heroicons.com/#:~:text=translate-,trash,-Copy%20SVG
コピー→https://heroicons.com/#:~:text=download-,duplicate,-Copy%20SVG
チェック→https://heroicons.com/#:~:text=check%2Dcircle-,check,-Copy%20SVG
外部リンク→https://heroicons.com/#:~:text=exclamation-,external%2Dlink,-Copy%20SVG
ログアウト→https://heroicons.com/#:~:text=login-,logout,-Copy%20SVG
タスク追加→https://heroicons.com/#:~:text=play-,plus%2Dcircle,-Copy%20SVG
ダミーアイコン→https://heroicons.com/#:~:text=user%2Dadd-,user%2Dcircle,-Copy%20SVG
閉じる→https://heroicons.com/#:~:text=x%2Dcircle-,x,-Copy%20SVG
設定→https://heroicons.com/#:~:text=code-,cog,-Copy%20SVG
戻る→https://heroicons.com/#:~:text=chevron%2Ddown-,chevron%2Dleft,-Copy%20SVG
進む→https://heroicons.com/#:~:text=chevron%2Dleft-,chevron%2Dright,-Copy%20SVG
プラス→https://heroicons.com/#:~:text=plus%2Dcircle-,plus%2Dsm,-Copy%20SVG

**Comment by ogakuzuko** [comment]
@miyasan31 
ダークモードなどのテーマ設定に対応するなら柔軟に色変えられる方がよさそうですね！🙆‍♀️ 

個人的にはHeroiconsに統一する方向でよいかと思いました！👍 

Figmaのを使うのはロゴぐらいになるのかな？👀

**Comment by miyasan31** [comment]
では統一していく方向で 🙆‍♂️

そうですね！ロゴはnext-themeのuseThemeから取れるresolvedThemeのkeyを見て、fillを動的に変更する感じでいけそうな感じがします！

---

#58 このプルリク内で CloseIcon、ChevronLeftIconが既にHeroIconから引用して実装してるので、それに倣ってこのissueのプルリク出したいと思います！もしくはこのプルリクでやっちゃいますかね？

**Comment by ogakuzuko** [comment]
@miyasan31 

変更箇所そこまで多くなさそうならまとめてしまってよいかも！🙆‍♀️

**Comment by miyasan31** [comment]
かしこまりました！
